name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: git
      run: git pull
      
    - name: Run docker compose
      run: docker compose restart
