name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    
    - name: GitPull 
      run: git pull
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Run docker compose
      run: docker compose restart
