name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: List current folder
      run: ls -la
      
    - name: Run docker compose
      run: docker compose restart
