name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Create zip deployment package 
      run : zip -r zip_file.zip ./ -x *.git*
      
    - name: Copy zip folder
      run :  cp -i zip_file.zip /home/admin/web/
    
    - name: List current folder
      run: ls -la
      
    - name: Run docker compose
      run: docker compose restart
