name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      
    - name: Run docker compose
      run: docker compose restart
