name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Start containers
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "docker-compose.yml"
        services: |
          docker compose up

